[project]
name = "testmol"
version = "0.0.3"
description = ""
authors = []
readme = "README.md"
requires-python = "==3.11.*"

dependencies = ["fibonacci_cpp", "fibonacci_cy"]

[tool.uv.sources]
fibonacci_cpp = { workspace = true }
fibonacci_cy = { workspace = true }

[tool.uv.workspace]
members = ["packages/*"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"