[project]
name = "testmol"
version = "0.0.3"
description = ""
authors = []
readme = "README.md"
requires-python = "==3.11.*"

dependencies = []

[build-system]
requires = ["meson-python"]
build-backend = "mesonpy"