# Workflow to build and test wheels.
# in the get_commit_message job include "build wheel" in your commit
# message to trigger the build.
name: Wheel builder

on:
    schedule:
    #        ┌───────────── minute (0 - 59)
    #        │  ┌───────────── hour (0 - 23)
    #        │  │ ┌───────────── day of the month (1 - 31)
    #        │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │  │ │ │ │
    - cron: "9  9 * * *"
    push:
        branches:
            - '*'
    pull_request:
        branches:
            - main
            - dev
    workflow_dispatch:

permissions:
    contents: read

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    get_commit_message:
        name: Get commit message
        runs-on: ubuntu-latest
        outputs:
            message: ${{ steps.commit_message.outputs.message }}
        steps:
          - name: Checkout
            uses: actions/checkout@v4
            with:
                fetch-depth: 0
          - name: Get commit message
            id: commit_message
            run: |
              set -xe
              COMMIT_MSG=$(git log --no-merges -1)
              RUN="0"
              if [[ "$COMMIT_MSG" == *"build wheel"* ]]; then
                  RUN="1"
              fi
              echo "message=$RUN" >> $GITHUB_OUTPUT
              echo github.ref ${{ github.ref }}
    
    build_wheels:
        name: ${{ matrix.python[0] }}-${{ matrix.buildplat[1] }}-${{ matrix.buildplat[2] }}
        needs: get_commit_message
        if: >-
            contains(needs.get_commit_message.outputs.message, '1') ||
            github.event_name == 'schedule' ||
            github.event_name == 'workflow_dispatch'
        runs-on: ${{ matrix.buildplat[0] }}
    
        strategy:
            # Ensure that a wheel builder finishes even if another fails
            fail-fast: false
            matrix:
                buildplat:
                - [ubuntu-22.04, manylinux, x86_64]
                - [ubuntu-22.04, musllinux, x86_64]
                - [ubuntu-24.04-arm, manylinux, aarch64]
                - [ubuntu-24.04-arm, musllinux, aarch64]
                # - [macos-13, macosx, x86_64]
                # - [macos-13, macosx, x86_64]
                # - [macos-14, macosx, arm64]
                # - [macos-14, macosx, arm64]
                # - [windows-2019, win, AMD64]
                python: [["cp311", "3.11"], ["cp312", "3.12"], ["cp313", "3.13"]]
                # matrix.python[0] is used to specify the python versions made by cibuildwheel
    
        # env:
            # TODO: upload behaviour
            # # upload to staging if it's a push to a maintenance branch and the last
            # # commit message contains '[wheel build]'
            # IS_PUSH: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/heads/maintenance') && contains(needs.get_commit_message.outputs.message, '1') }}
            # IS_SCHEDULE_DISPATCH: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    
        steps:
          - name: Checkout
            uses: actions/checkout@v4
            with:
                fetch-depth: 0

          - uses: actions/setup-python@v5
            with:
                python-version: 3.11

          - name: Install project build system requirements (ninja)
            run: sudo apt-get update && sudo apt-get install -y ninja-build
            if: ${{ runner.os == 'Linux' }}
    
        #   - name: win_amd64 - install rtools
        #     run: |
        #       # mingw-w64
        #       choco install rtools -y --no-progress --force --version=4.0.0.20220206
        #       echo "c:\rtools40\ucrt64\bin;" >> $env:GITHUB_PATH
        #     if: ${{ runner.os == 'Windows' }}

        #   - name: windows - set PKG_CONFIG_PATH
        #     if: ${{ runner.os == 'Windows' }}
        #     run: |
        #         $env:CIBW = "${{ github.workspace }}"
        #         # It seems somewhere in the env passing, `\` is not
        #         # passed through, so convert it to '/'
        #         $env:CIBW=$env:CIBW.replace("\","/")
        #         echo "CIBW_ENVIRONMENT=PKG_CONFIG_PATH=$env:CIBW" >> $env:GITHUB_ENV


          - name: Build wheels (cibuildwheel)
            uses: pypa/cibuildwheel@d04cacbc9866d432033b1d09142936e6a0e2121a # v2.23.2
            env:
                CIBW_BUILD: ${{ matrix.python[0] }}-${{ matrix.buildplat[1] }}*
                CIBW_ARCHS: ${{ matrix.buildplat[2] }}
                # CIBW_PRERELEASE_PYTHONS: True
                # CIBW_FREE_THREADED_SUPPORT: True

          - uses: actions/upload-artifact@v4
            with:
                path: ./wheelhouse/*.whl
                name: ${{ matrix.python[0] }}-${{ matrix.buildplat[1] }}-${{ matrix.buildplat[2] }}
                retention-days: 1

        # TODO: upload wheels  (possibly based on IS_PUSH or IS_SCHEDULE_DISPATCH)